# Generated by Django 4.1.2 on 2024-06-10 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
    ]
