# Generated by Django 4.1.2 on 2024-06-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_remove_cliente_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='id_genero',
            field=models.CharField(db_column='idGenero', max_length=10, primary_key=True, serialize=False),
        ),
    ]
