# Generated by Django 4.1.2 on 2024-06-11 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_genero_id_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genero',
            old_name='id_genero',
            new_name='idgenero',
        ),
    ]
