# Generated by Django 4.1.2 on 2024-06-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_rename_id_genero_genero_idgenero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='idgenero',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
