# Generated by Django 4.1.2 on 2024-06-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_cliente_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contraseña',
            field=models.CharField(max_length=10),
        ),
    ]
