# Generated by Django 4.1.2 on 2024-06-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_juegos_pc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos_pc',
            name='imagen',
            field=models.ImageField(upload_to='cliente'),
        ),
    ]
