# Generated by Django 4.1.2 on 2024-06-21 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_juegos_ps4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Juegos',
            fields=[
                ('idcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Juegos',
            fields=[
                ('idjuego', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('puntuacion', models.CharField(max_length=2)),
                ('precio', models.CharField(max_length=20)),
                ('imagen', models.ImageField(upload_to='cliente')),
                ('id_categoria', models.ForeignKey(db_column='idcategoria', on_delete=django.db.models.deletion.CASCADE, to='cliente.categoria_juegos')),
            ],
        ),
        migrations.DeleteModel(
            name='Juegos_Pc',
        ),
        migrations.DeleteModel(
            name='Juegos_Ps4',
        ),
        migrations.DeleteModel(
            name='Juegos_Ps5',
        ),
    ]
