# Generated by Django 4.1.2 on 2024-06-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0012_categoria_juegos_juegos_delete_juegos_pc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juegos_Pc',
            fields=[
                ('idjuego', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('puntuacion', models.CharField(max_length=2)),
                ('precio', models.CharField(max_length=20)),
                ('imagen', models.ImageField(upload_to='cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Juegos_Ps4',
            fields=[
                ('idjuego', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('puntuacion', models.CharField(max_length=2)),
                ('precio', models.CharField(max_length=20)),
                ('imagen', models.ImageField(upload_to='cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Juegos_Ps5',
            fields=[
                ('idjuego', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('puntuacion', models.CharField(max_length=2)),
                ('precio', models.CharField(max_length=20)),
                ('imagen', models.ImageField(upload_to='cliente')),
            ],
        ),
        migrations.RemoveField(
            model_name='juegos',
            name='id_categoria',
        ),
        migrations.DeleteModel(
            name='Categoria_Juegos',
        ),
        migrations.DeleteModel(
            name='Juegos',
        ),
    ]
