# Generated by Django 4.1.2 on 2024-06-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0014_categoria_juegos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categoria_juegos',
        ),
    ]
