# Generated by Django 4.1.2 on 2024-06-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0015_rename_categoria_categoria_juegos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Juegos_Pc',
        ),
        migrations.DeleteModel(
            name='Juegos_Ps4',
        ),
        migrations.DeleteModel(
            name='Juegos_Ps5',
        ),
    ]
