# Generated by Django 4.1.2 on 2024-06-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0017_puntuacion_juegos_alter_juegos_puntuacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Puntuacion_juegos',
        ),
    ]
