# Generated by Django 4.1.2 on 2024-06-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0018_delete_puntuacion_juegos'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='video',
            field=models.FileField(default=2, upload_to='cliente/videos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='juegos',
            name='imagen',
            field=models.ImageField(upload_to='cliente/img'),
        ),
    ]
