# Generated by Django 4.1.2 on 2024-06-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0019_juegos_video_alter_juegos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='imagen',
            field=models.ImageField(upload_to='cliente'),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='video',
            field=models.FileField(upload_to='cliente'),
        ),
    ]
