# Generated by Django 4.1.2 on 2024-06-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0020_alter_juegos_imagen_alter_juegos_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='estreno',
            field=models.BooleanField(default=1, verbose_name=True),
            preserve_default=False,
        ),
    ]
