# Generated by Django 4.1.2 on 2024-06-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0021_juegos_estreno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='estreno',
            field=models.BooleanField(default=False),
        ),
    ]
