# Generated by Django 4.1.2 on 2024-06-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0022_alter_juegos_estreno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrousel_2025',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='cliente')),
            ],
        ),
    ]
