# Generated by Django 4.1.2 on 2024-06-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0023_carrousel_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idcarrito', models.AutoField(primary_key=True, serialize=False)),
                ('run_cliente', models.CharField(max_length=10)),
                ('precio_total', models.CharField(max_length=20)),
                ('juegos', models.ManyToManyField(to='cliente.juegos')),
            ],
        ),
    ]
