# Generated by Django 4.1.2 on 2024-06-29 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0024_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='carrito',
            field=models.ForeignKey(db_column='idcarrito', default=1, on_delete=django.db.models.deletion.CASCADE, to='cliente.carrito'),
            preserve_default=False,
        ),
    ]
