# Generated by Django 4.1.2 on 2024-06-29 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0025_cliente_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='carrito',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
