# Generated by Django 4.1.2 on 2024-06-29 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0026_remove_cliente_carrito_delete_carrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idcarrito', models.AutoField(primary_key=True, serialize=False)),
                ('run_cliente', models.CharField(max_length=10)),
                ('precio_total', models.CharField(max_length=20)),
                ('juegos', models.ManyToManyField(to='cliente.juegos')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='carrito',
            field=models.ForeignKey(db_column='idcarrito', default=1, on_delete=django.db.models.deletion.CASCADE, to='cliente.carrito'),
            preserve_default=False,
        ),
    ]
