# Generated by Django 4.1.2 on 2024-06-29 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0027_carrito_cliente_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='carrito',
            field=models.ForeignKey(db_column='idcarrito', null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.carrito'),
        ),
    ]
