# Generated by Django 4.1.2 on 2024-06-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0028_alter_cliente_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='run_cliente',
        ),
        migrations.AddField(
            model_name='carrito',
            name='correo_cliente',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
