# Generated by Django 4.1.2 on 2024-06-30 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0031_cliente_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
    ]
