# Generated by Django 4.1.2 on 2024-06-30 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0033_cliente_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.carrito')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.juegos')),
            ],
        ),
    ]
