# Generated by Django 4.1.2 on 2024-06-30 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0034_carritojuego'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarritoJuego',
        ),
    ]
