# Generated by Django 4.1.2 on 2024-06-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0035_delete_carritojuego'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='cantidad_jugadores',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juegos',
            name='mas18',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='juegos',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
