# Generated by Django 4.1.2 on 2024-07-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0037_alter_carrito_precio_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='juegos',
            field=models.ManyToManyField(default=None, null=True, to='cliente.juegos'),
        ),
    ]
