# Generated by Django 4.1.2 on 2024-07-01 04:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0038_alter_carrito_juegos'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrito_cantidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.carrito')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.juegos')),
            ],
        ),
    ]
