# Generated by Django 4.1.2 on 2024-07-01 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0039_carrito_cantidad'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carrito_cantidad',
            unique_together={('carrito', 'juego')},
        ),
    ]
