# Generated by Django 4.1.2 on 2024-07-01 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0041_alter_carrito_cantidad_cantidad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='carrito_cantidad',
        ),
    ]
