# Generated by Django 4.1.13 on 2024-07-02 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0042_delete_carrito_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='juegos',
        ),
    ]
