# Generated by Django 4.1.13 on 2024-07-02 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0043_remove_carrito_juegos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CantJuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.carrito')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.juegos')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='juegos',
            field=models.ManyToManyField(through='cliente.CantJuegos', to='cliente.juegos'),
        ),
    ]
