# Generated by Django 4.1.13 on 2024-07-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0044_cantjuegos_carrito_juegos'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
