# Generated by Django 4.1.13 on 2024-07-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0045_carrito_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='stock',
        ),
        migrations.AddField(
            model_name='juegos',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
