# Generated by Django 4.1.13 on 2024-07-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0048_alter_juegos_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
