# Generated by Django 4.1.13 on 2024-07-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0051_alter_juegos_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='video',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
