# Generated by Django 4.1.13 on 2024-07-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0053_alter_juegos_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuegosPagados',
            fields=[
                ('idpeticion', models.AutoField(primary_key=True, serialize=False)),
                ('correo_cliente', models.EmailField(blank=True, max_length=100, unique=True)),
                ('precio_total', models.CharField(default=0, max_length=20, null=True)),
                ('juegos', models.ManyToManyField(to='cliente.juegos')),
            ],
        ),
    ]
