# Generated by Django 4.1.13 on 2024-07-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0054_juegospagados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegospagados',
            name='correo_cliente',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
